"""
Django settings for qualix_dev project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9v&w*+eeymdp91%5wj=xs(=o-v$@48^j*-$tf5fb@-+gy)g-hi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',  # Приложение "api" зарегистрировано
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qualix_dev.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'api/templates'],  # Шаблоны находятся здесь
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qualix_dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Добавляем содержимое сертификата и ключа
CERTIFICATE_CONTENT = """
-----BEGIN CERTIFICATE-----
MIIDNjCCAh4CAwX1szANBgkqhkiG9w0BAQsFADBpMQswCQYDVQQGEwJSVTEMMAoG
A1UECAwDVWZhMQwwCgYDVQQHDANVZmExDDAKBgNVBAoMA3NsYjEMMAoGA1UEAwwD
c2xiMSIwIAYJKoZIhvcNAQkBFhNzdXBwb3J0QHNsYi5tZWR2LnJ1MB4XDTI0MDYy
NDEyMDAxOVoXDTI1MDYyNDEyMDAxOVowVzELMAkGA1UEBhMCUlUxDzANBgNVBAgM
Bk1vc2NvdzEPMA0GA1UEBwwGTW9zY293MQ0wCwYDVQQKDARUZXN0MRcwFQYDVQQD
DA50ZXN0QHRlc3QudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AJWdgDfGwHt4tQc7SQdZrI2y6EMn25t28xL7LFRsx0J1FjCei5+0m+PSN57VyETG
6ZAJGgKgkfgoDHCBxz5iLAw38tSpKxR4RvVlnsWgOi7i/eix75SN5mO0qZVkVcht
cWbvSsfCxyrSpjIRhk7P5p6cQczNLpsglm2yK7+1XhXTHH//OGQrm4bVWh2wInYu
d0uVPpApqnprHvHM5WgY4+8enAOqXa+wcZ2JNv/jTOE9w/dnjY5A3GjOmYB2evmu
4VafVdQgOpE+RXIoHMxnrnQRjgLVV1KaG9vn5aUOYgeaLe7rTrVttXc2OaietdEx
32cJCGlGtdEdJxfbsFXmMNcCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEACqiZoku2
YQFqQ/h56WqEZtehYuS7ia3XfhOTKN5jeTV3R2dFc7waxu6hCwNIHdi+rFUffJu/
vszrVbtQIoRZv3H0x0e8ZoMfdgws4xkAcdmQ6jA7MdPd/LBMPFmz9vN9N/i1uwPh
OTBqIuY8fXxwSolpqgAv2qHb7gPcSTLQfhGgcC9txSFJbQAae2lOBz5LrPMH4wfG
5NNQkLnJOfPT9aXKh0ebmYYlUlgGIbU2BqlhklMVyyDA8mU6gq/+0iI667efh/tA
UvwT7ElfIUFyZmQKyquHlUgl4jCRn3jC6IJjXtL7vvJ9D+iNCp6vz02iAdW/dCoT
EYJi14GirXpX0g==
-----END CERTIFICATE-----
"""

KEY_CONTENT = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVnYA3xsB7eLUH
...
-----END PRIVATE KEY-----
"""

# URL для JSON-RPC сервиса
JSONRPC_ENDPOINT = "https://slb.medv.ru/api/v2/"
